import shutil
import os
from pathlib import Path

# ---------------------------------------------------------
# Configuración general del proceso de limpieza
# ---------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

MODEL_DIR = BASE_DIR / "models" / "qwen2.5-3b-lora-eventgrid"
LOG_PATH = BASE_DIR / "logs" / "train_lora.log"
CHECKPOINT_DIR = BASE_DIR / "models" / "checkpoint"  # Por si Transformers genera checkpoints

TARGETS = [
    MODEL_DIR,
    LOG_PATH,
    CHECKPOINT_DIR,
]

# ---------------------------------------------------------
# Ejecución del proceso de limpieza
# ---------------------------------------------------------

def purge():
    """Remove only the outputs generated by train_lora.py."""
    print("\n=== Purge Script: train_lora.py Outputs ===\n")

    for target in TARGETS:
        if target.exists():
            try:
                if target.is_dir():
                    shutil.rmtree(target)
                    print(f"[OK] Deleted directory: {target}")
                else:
                    os.remove(target)
                    print(f"[OK] Deleted file: {target}")
            except Exception as e:
                print(f"[ERROR] Could not delete {target}: {e}")
        else:
            print(f"[SKIP] Not found: {target}")

    print("\n=== DONE ===\n")

# ---------------------------------------------------------
# Entry point
# ---------------------------------------------------------

if __name__ == "__main__":
    purge()
