import os
from pathlib import Path

# ---------------------------------------------------------
# Configuración general del proceso de limpieza
# ---------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
LOG_PATH = BASE_DIR / "logs" / "rag_query.log"

FILES_TO_DELETE = [
    LOG_PATH,
]

# ---------------------------------------------------------
# Ejecución del proceso de limpieza
# ---------------------------------------------------------

def purge():
    """Remove only the outputs generated by Script 8 (RAG Query)."""
    print("\n=== Purge Script 8: RAG Query Outputs ===\n")

    for file_path in FILES_TO_DELETE:
        if file_path.exists():
            try:
                os.remove(file_path)
                print(f"[OK] Deleted: {file_path}")
            except Exception as e:
                print(f"[ERROR] Could not delete {file_path}: {e}")
        else:
            print(f"[SKIP] Not found: {file_path}")

    print("\n=== DONE ===\n")

# ---------------------------------------------------------
# Entry point
# ---------------------------------------------------------

if __name__ == "__main__":
    purge()
