services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - ollama_data:/root/.ollama

  pytorch-rocm:
    image: rocm/pytorch:rocm7.2_ubuntu24.04_py3.12_pytorch_release_2.9.1
    container_name: pytorch-rocm
    stdin_open: true
    tty: true
    restart: "no"
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    shm_size: "16g"
    volumes:
      - /home/robece/Documents/eventgrid-expert:/workspace
    working_dir: /workspace
    command: bash
    environment:
      - AZURE_OPENAI_KEY=
      - AZURE_OPENAI_ENDPOINT=
      - AZURE_OPENAI_API_VERSION=
      - HF_TOKEN=
volumes:
  ollama_data:
