services:
  eventgrid-api:
    image: robece/eventgrid-api:1.0
    build:
      context: /home/robece/Documents/eventgrid-expert
      dockerfile: api/Dockerfile
    container_name: eventgrid-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    shm_size: "16g"
    volumes:
      - /home/robece/Documents/eventgrid-expert/api/logs:/logs
    environment:
      - HF_TOKEN=
      - AZURE_OPENAI_KEY=
      - AZURE_OPENAI_ENDPOINT=
      - AZURE_OPENAI_API_VERSION=
